namespace OpenQbit.Institute.DAL.DataAccess.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class DBInt20170607modifymodels : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Batch", "Branch_Id", "dbo.Branch");
            DropForeignKey("dbo.Branch", "InstituteId", "dbo.Institut");
            DropForeignKey("dbo.BatchEnrolment", "Batch_Id", "dbo.Batch");
            DropForeignKey("dbo.BatchEnrolment", "Student_Id", "dbo.Student");
            DropForeignKey("dbo.SubjectEnrolment", "Student_Id", "dbo.Student");
            DropForeignKey("dbo.Lecture", "SubjectID", "dbo.Subject");
            DropForeignKey("dbo.SubjectEnrolment", "SubjectId", "dbo.Subject");
            DropForeignKey("dbo.Student", "ParentInformationId", "dbo.ParentInformation");
            DropIndex("dbo.Batch", new[] { "Branch_Id" });
            DropIndex("dbo.Branch", new[] { "InstituteId" });
            DropIndex("dbo.BatchEnrolment", new[] { "Batch_Id" });
            DropIndex("dbo.BatchEnrolment", new[] { "Student_Id" });
            DropIndex("dbo.SubjectEnrolment", new[] { "Student_Id" });
            DropColumn("dbo.Batch", "BranchId");
            DropColumn("dbo.BatchEnrolment", "BatchId");
            DropColumn("dbo.BatchEnrolment", "StudentId");
            DropColumn("dbo.SubjectEnrolment", "StudentId");
            RenameColumn(table: "dbo.Batch", name: "Branch_Id", newName: "BranchId");
            RenameColumn(table: "dbo.BatchEnrolment", name: "Batch_Id", newName: "BatchId");
            RenameColumn(table: "dbo.BatchEnrolment", name: "Student_Id", newName: "StudentId");
            RenameColumn(table: "dbo.SubjectEnrolment", name: "Student_Id", newName: "StudentId");
            DropPrimaryKey("dbo.Batch");
            DropPrimaryKey("dbo.Branch");
            DropPrimaryKey("dbo.Institut");
            DropPrimaryKey("dbo.BatchEnrolment");
            DropPrimaryKey("dbo.BranchResourceAllocation");
            DropPrimaryKey("dbo.Subject");
            DropPrimaryKey("dbo.ParentInformation");
            DropPrimaryKey("dbo.Student");
            DropPrimaryKey("dbo.SubjectEnrolment");
            AddColumn("dbo.Batch", "BatchId", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.Branch", "BranchId", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.Branch", "Institute_InstitutId", c => c.Int());
            AddColumn("dbo.Institut", "InstitutId", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.BatchEnrolment", "BatchEnrolmentId", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.BranchResourceAllocation", "BranchResourceAllocationId", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.Lecture", "EmployeeId", c => c.Int(nullable: false));
            AddColumn("dbo.Subject", "SubjectId", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.ParentInformation", "ParentInformationId", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.Staff", "EmployeeId", c => c.Int(nullable: false));
            AddColumn("dbo.Student", "StudentId", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.Student", "PersonId", c => c.Int(nullable: false));
            AddColumn("dbo.SubjectEnrolment", "SubjectEnrolmentId", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Batch", "BranchId", c => c.Int(nullable: false));
            AlterColumn("dbo.BatchEnrolment", "BatchId", c => c.Int(nullable: false));
            AlterColumn("dbo.BatchEnrolment", "StudentId", c => c.Int(nullable: false));
            AlterColumn("dbo.SubjectEnrolment", "StudentId", c => c.Int(nullable: false));
            AddPrimaryKey("dbo.Batch", "BatchId");
            AddPrimaryKey("dbo.Branch", "BranchId");
            AddPrimaryKey("dbo.Institut", "InstitutId");
            AddPrimaryKey("dbo.BatchEnrolment", "BatchEnrolmentId");
            AddPrimaryKey("dbo.BranchResourceAllocation", "BranchResourceAllocationId");
            AddPrimaryKey("dbo.Subject", "SubjectId");
            AddPrimaryKey("dbo.ParentInformation", "ParentInformationId");
            AddPrimaryKey("dbo.Student", "StudentId");
            AddPrimaryKey("dbo.SubjectEnrolment", "SubjectEnrolmentId");
            CreateIndex("dbo.Batch", "BranchId");
            CreateIndex("dbo.Branch", "Institute_InstitutId");
            CreateIndex("dbo.BatchEnrolment", "BatchId");
            CreateIndex("dbo.BatchEnrolment", "StudentId");
            CreateIndex("dbo.Lecture", "EmployeeId");
            CreateIndex("dbo.Staff", "EmployeeId");
            CreateIndex("dbo.Student", "PersonId");
            CreateIndex("dbo.SubjectEnrolment", "StudentId");
            AddForeignKey("dbo.Lecture", "EmployeeId", "dbo.Employee", "EmployeeID", cascadeDelete: true);
            AddForeignKey("dbo.Staff", "EmployeeId", "dbo.Employee", "EmployeeID", cascadeDelete: true);
            AddForeignKey("dbo.Student", "PersonId", "dbo.Person", "PersonId", cascadeDelete: true);
            AddForeignKey("dbo.Batch", "BranchId", "dbo.Branch", "BranchId", cascadeDelete: true);
            AddForeignKey("dbo.Branch", "Institute_InstitutId", "dbo.Institut", "InstitutId");
            AddForeignKey("dbo.BatchEnrolment", "BatchId", "dbo.Batch", "BatchId", cascadeDelete: true);
            AddForeignKey("dbo.BatchEnrolment", "StudentId", "dbo.Student", "StudentId", cascadeDelete: true);
            AddForeignKey("dbo.SubjectEnrolment", "StudentId", "dbo.Student", "StudentId", cascadeDelete: true);
            AddForeignKey("dbo.Lecture", "SubjectID", "dbo.Subject", "SubjectId", cascadeDelete: true);
            AddForeignKey("dbo.SubjectEnrolment", "SubjectId", "dbo.Subject", "SubjectId", cascadeDelete: true);
            AddForeignKey("dbo.Student", "ParentInformationId", "dbo.ParentInformation", "ParentInformationId", cascadeDelete: true);
            DropColumn("dbo.Batch", "Id");
            DropColumn("dbo.Branch", "Id");
            DropColumn("dbo.Institut", "Id");
            DropColumn("dbo.BatchEnrolment", "Id");
            DropColumn("dbo.BranchResourceAllocation", "Id");
            DropColumn("dbo.Subject", "Id");
            DropColumn("dbo.ParentInformation", "Id");
            DropColumn("dbo.Student", "Id");
            DropColumn("dbo.SubjectEnrolment", "Id");
        }
        
        public override void Down()
        {
            AddColumn("dbo.SubjectEnrolment", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.Student", "Id", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.ParentInformation", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.Subject", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.BranchResourceAllocation", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.BatchEnrolment", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.Institut", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.Branch", "Id", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.Batch", "Id", c => c.String(nullable: false, maxLength: 128));
            DropForeignKey("dbo.Student", "ParentInformationId", "dbo.ParentInformation");
            DropForeignKey("dbo.SubjectEnrolment", "SubjectId", "dbo.Subject");
            DropForeignKey("dbo.Lecture", "SubjectID", "dbo.Subject");
            DropForeignKey("dbo.SubjectEnrolment", "StudentId", "dbo.Student");
            DropForeignKey("dbo.BatchEnrolment", "StudentId", "dbo.Student");
            DropForeignKey("dbo.BatchEnrolment", "BatchId", "dbo.Batch");
            DropForeignKey("dbo.Branch", "Institute_InstitutId", "dbo.Institut");
            DropForeignKey("dbo.Batch", "BranchId", "dbo.Branch");
            DropForeignKey("dbo.Student", "PersonId", "dbo.Person");
            DropForeignKey("dbo.Staff", "EmployeeId", "dbo.Employee");
            DropForeignKey("dbo.Lecture", "EmployeeId", "dbo.Employee");
            DropIndex("dbo.SubjectEnrolment", new[] { "StudentId" });
            DropIndex("dbo.Student", new[] { "PersonId" });
            DropIndex("dbo.Staff", new[] { "EmployeeId" });
            DropIndex("dbo.Lecture", new[] { "EmployeeId" });
            DropIndex("dbo.BatchEnrolment", new[] { "StudentId" });
            DropIndex("dbo.BatchEnrolment", new[] { "BatchId" });
            DropIndex("dbo.Branch", new[] { "Institute_InstitutId" });
            DropIndex("dbo.Batch", new[] { "BranchId" });
            DropPrimaryKey("dbo.SubjectEnrolment");
            DropPrimaryKey("dbo.Student");
            DropPrimaryKey("dbo.ParentInformation");
            DropPrimaryKey("dbo.Subject");
            DropPrimaryKey("dbo.BranchResourceAllocation");
            DropPrimaryKey("dbo.BatchEnrolment");
            DropPrimaryKey("dbo.Institut");
            DropPrimaryKey("dbo.Branch");
            DropPrimaryKey("dbo.Batch");
            AlterColumn("dbo.SubjectEnrolment", "StudentId", c => c.String(maxLength: 128));
            AlterColumn("dbo.BatchEnrolment", "StudentId", c => c.String(maxLength: 128));
            AlterColumn("dbo.BatchEnrolment", "BatchId", c => c.String(maxLength: 128));
            AlterColumn("dbo.Batch", "BranchId", c => c.String(maxLength: 128));
            DropColumn("dbo.SubjectEnrolment", "SubjectEnrolmentId");
            DropColumn("dbo.Student", "PersonId");
            DropColumn("dbo.Student", "StudentId");
            DropColumn("dbo.Staff", "EmployeeId");
            DropColumn("dbo.ParentInformation", "ParentInformationId");
            DropColumn("dbo.Subject", "SubjectId");
            DropColumn("dbo.Lecture", "EmployeeId");
            DropColumn("dbo.BranchResourceAllocation", "BranchResourceAllocationId");
            DropColumn("dbo.BatchEnrolment", "BatchEnrolmentId");
            DropColumn("dbo.Institut", "InstitutId");
            DropColumn("dbo.Branch", "Institute_InstitutId");
            DropColumn("dbo.Branch", "BranchId");
            DropColumn("dbo.Batch", "BatchId");
            AddPrimaryKey("dbo.SubjectEnrolment", "Id");
            AddPrimaryKey("dbo.Student", "Id");
            AddPrimaryKey("dbo.ParentInformation", "Id");
            AddPrimaryKey("dbo.Subject", "Id");
            AddPrimaryKey("dbo.BranchResourceAllocation", "Id");
            AddPrimaryKey("dbo.BatchEnrolment", "Id");
            AddPrimaryKey("dbo.Institut", "Id");
            AddPrimaryKey("dbo.Branch", "Id");
            AddPrimaryKey("dbo.Batch", "Id");
            RenameColumn(table: "dbo.SubjectEnrolment", name: "StudentId", newName: "Student_Id");
            RenameColumn(table: "dbo.BatchEnrolment", name: "StudentId", newName: "Student_Id");
            RenameColumn(table: "dbo.BatchEnrolment", name: "BatchId", newName: "Batch_Id");
            RenameColumn(table: "dbo.Batch", name: "BranchId", newName: "Branch_Id");
            AddColumn("dbo.SubjectEnrolment", "StudentId", c => c.Int(nullable: false));
            AddColumn("dbo.BatchEnrolment", "StudentId", c => c.Int(nullable: false));
            AddColumn("dbo.BatchEnrolment", "BatchId", c => c.Int(nullable: false));
            AddColumn("dbo.Batch", "BranchId", c => c.Int(nullable: false));
            CreateIndex("dbo.SubjectEnrolment", "Student_Id");
            CreateIndex("dbo.BatchEnrolment", "Student_Id");
            CreateIndex("dbo.BatchEnrolment", "Batch_Id");
            CreateIndex("dbo.Branch", "InstituteId");
            CreateIndex("dbo.Batch", "Branch_Id");
            AddForeignKey("dbo.Student", "ParentInformationId", "dbo.ParentInformation", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SubjectEnrolment", "SubjectId", "dbo.Subject", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Lecture", "SubjectID", "dbo.Subject", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SubjectEnrolment", "Student_Id", "dbo.Student", "Id");
            AddForeignKey("dbo.BatchEnrolment", "Student_Id", "dbo.Student", "Id");
            AddForeignKey("dbo.BatchEnrolment", "Batch_Id", "dbo.Batch", "Id");
            AddForeignKey("dbo.Branch", "InstituteId", "dbo.Institut", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Batch", "Branch_Id", "dbo.Branch", "Id");
        }
    }
}
